### ISSUE TITLE
M-CMP v0.2.0 release plan

### ISSUE THREAD

**Issue by seokho-son** [m-cmp/m-cmp#7]
# M-CMP v0.2.0 릴리스 추진 계획 (1차 변경)

## 릴리스 일정 및 대상

- 릴리스 리드 : (주) 손석호, (부) 각 저장소 메인테이너
- 릴리스 목표일: ~~2024. 06. 28(금) 오후 3시~~ **2024. 07. 05(금) 오후 3시**
- 통합 프리릴리스 목표일: ~~2024. 06. 18(화) 오후 3시~~ **2024. 06. 26(수) 오후 3시**

- 릴리스 대상 저장소 (check: 완료)
  - [x] https://github.com/m-cmp/mc-web-console
  - [x] https://github.com/m-cmp/mc-workflow-manager
  - [x] https://github.com/m-cmp/mc-application-manager (참고: mc-workflow-manager 에서 통합 개발되고 있음. 향후 정리)
  - [x] https://github.com/m-cmp/mc-observability
  - [x] https://github.com/m-cmp/mc-infra-manager (submodule: [CB-Tumblebug](https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.8.13))
  - [x] https://github.com/m-cmp/mc-infra-connector (submodule: CB-Spider)

- 비 대상
  - https://github.com/m-cmp/mc-across-service-manager 
  - https://github.com/m-cmp/mc-iam-manager (CB-TB 와 연동 테스트 추진)
  - https://github.com/m-cmp/mc-admin-cli
  - https://github.com/m-cmp/mc-cost-optimizer

## 통합 및 연동 테스트 방법 (담당: 전체)

- 통합 및 연동 테스트 목적 (v0.2.0)
  - 서브시스템간 API를 통해 기본 시나리오를 유기적으로 수행할 수 있는 통합 시스템 기반 확보 
  - 하반기 완전한 통합 시스템 릴리스(v0.3.0)를 대비하여 선행 작업 (v0.3.0 포함 기능은 올해 풀 스펙을 목표로 함)
  - 기본 연동 시나리오와 무관한 기능은 v0.2.0에서는 제외 가능
  - Look & feel 보다는 서브시스템간 유연한 기능 통합에 주안을 둘 필요 (별도의 공개 시연은 없음. 내부 검토용 시연 진행 예정)

- 통합 및 필수 연동 대상
  - [x] https://github.com/m-cmp/mc-web-console
  - [x] https://github.com/m-cmp/mc-workflow-manager
  - [x] https://github.com/m-cmp/mc-application-manager (참고: mc-workflow-manager에 통합 개발되고 있음)
  - [x] https://github.com/m-cmp/mc-observability
  - [x] https://github.com/m-cmp/mc-infra-manager (submodule: CB-Tumblebug)
  - [x] https://github.com/m-cmp/mc-infra-connector (submodule: CB-Spider)

- 선택적 통합 대상 (각 저장소 메인테이너가 판단: 기능 구동 성숙도 무관)
  - [x] https://github.com/m-cmp/mc-iam-manager (CB-TB 와 연동 테스트 추진)
  - [ ] https://github.com/m-cmp/mc-admin-cli
  - [ ] https://github.com/m-cmp/mc-cost-optimizer

- 기본 연동 시나리오
  - 운영자
    - 1) 시스템 구동 및 환경 설정
    - 2) 애플리케이션 등록 (이번 통합에서는 제외, 빌트인 애플리케이션 가정)

  - 사용자(워크플로우 미활용 경우)
    - 1) 웹 콘솔 접속
    - 2) ~~등록 애플리케이션 조회~~
    - 3) VM 인프라 생성
    - 4) ~~애플리케이션 배포~~
    - 5) ~~애플리케이션 접속 및 활용~~
    - 6) 인프라 리소스 모니터링 
    - 7) ~~클라우드 비용(사용량) 확인~~ 
    - 8) VM 인프라 종료 및 삭제

  - 사용자(워크플로우 활용 경우)
    - 1) 웹 콘솔 접속
    - 2) WF 등록 (인프라 및 애플리케이션 배포 구성)
    - 3) WF 조회/실행 (인프라 및 애플리케이션 통합 배포)
    - 4) 애플리케이션 접속 및 활용 
    - 5) 인프라 리소스 모니터링 
    - 6) ~~클라우드 비용(사용량) 확인~~ 
    - 7) VM 인프라 종료 및 삭제 (또는 삭제 WF 실행)
 
  ![image](https://github.com/m-cmp/m-cmp/assets/5966944/ce2d7959-16c4-420d-b325-889fe61a1dbf)

- 연동 기능: 기본 시나리오에 관련된 기능/UI 전체
   - 연동 시험 형상
     - VM 인프라 (총 6개 VM): 3종 CSP (AWS, Azure, GCP) 별 VM 2개 (Ubuntu 20.04 / Ubuntu 22.04 혼합)
       * 비고: 각 서브시스템 기능 연동시, 기관별로 CB-Tumblebug를 각자 구축 및 연동 테스트에 활용
     - 애플리케이션: 3종 (tomcat, redis, nginx 등)

### 통합 세부 일정

| 완료일정           | 작업                                                               | 대상 저장소 | 비고              |
| ------------------ | ------------------------------------------------------ | -- | -------------- |
| **05-10(금)** | 인프라 연동/관리 기능 프리릴리스 (CB-Spider, CB-Tumblebug v0.8.x)       |  CB-Spider, CB-Tumblebug     |  |
| **05-16(목)** | M-CMP 각 서브시스템 예정 API 문서 공유     |  API를 제공하는 통합 대상 저장소 전체     | 가급적 Swagger API 문서로 제공 (실제 구동 여부 무관) |
| ~~06-14(금)~~ **06-18(화)** | 각 서브시스템간 순차 연동 및 테스트 (1.CB-Spider -> 2.CB-Tumblebug -> 3.병렬{mc-observability, mc-application-manager, mc-workflow-manager} -> 4.mc-web-console   |    통합 대상 저장소 전체     | 기관별 세부 일정 댓글에 명시 완료, mc-web-console은 **06-26(수)** 까지 추진  |
| ~~06-18(화)~~ **06-26(수)**   | 통합 시나리오 연동 및 테스트      |    통합 대상 저장소 전체     |  mc-web-console를 통해서 시나리오 구동 확인 |
| **06-26(수)** | M-CMP 각 서브시스템 v0.1.x 전체 프리릴리스      |    통합 대상 저장소 전체     |   |
| **06-27(목)** **06-28(금)**   | M-CMP 워크샵 통합 시연 및 상호 리뷰      |    통합 대상 저장소 전체     |   |
| **07-02(화)**     | 각 서브시스템별 최종 확인/보완 및 각 서브시스템 저장소 v0.2.0 릴리스       | 통합 대상 저장소 전체  | 최종: ~ 07/03 18시 | 
| ~~06-28(금)~~ **07-05(금)**    | M-CMP platform v0.2.0 release                | m-cmp/m-cmp 저장소 |   |

## 저장소별 추진 상세 사항 (담당: 각 저장소 메인테이너)

- 개별 서브시스템 실행 지원
  - 스크립트 형태로 쉽게 설치 및 실행할 수 있는 방법 제공
  - Dockerfile을 구성하여, 컨테이너 구동 지원
    - 예시: https://github.com/cloud-barista/cb-tumblebug/blob/main/Dockerfile
    - 참고:  [GHCR, DockerHub로 배포 자동화 적용 예정](https://github.com/cloud-barista/cb-tumblebug/blob/main/.github/workflows/continuous-delivery.yaml)
  - 저장소별 릴리스 특이 사항 공유 (본 이슈의 코멘트에 기입)

- 문서화
  - Readme 업데이트 (Readme는 모든 정보를 v0.2.0으로 미리 지정)
  - API 문서 업데이트 및 링크 제공 (API 문서는 Swagger API로 제공 필수)
    - 참고: #2

- 프리릴리스 생성 (Tag: v0.1.x)
  - 프리릴리스는 필요에 따라 상시 진행
    - 타 서브시스템 연동 테스트를 위한 프리릴리스 수행 시, 커뮤니티에 전체 공지
  - 릴리스 포함 정보: tag (v0.1.x), title (v0.1.x), 내용 (API 문서 링크, 릴리스 노트-`Generate release notes` 자동생성 반영)
    - 스타일 참고: https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.8.9

## 통합 플랫폼 릴리스

**<ins>담당: ETRI 멤버</ins>**
**<ins>기한: 2024. 07. 05(금) 오후 3시</ins>**

- 통합 플랫폼 문서화
  - Base repository: https://github.com/m-cmp/docs

각 장소의 Pre-release v0.1.x 및 통합 테스트 수행사항을 바탕으로 통합 플랫폼 릴리스를 진행

- https://github.com/m-cmp/m-cmp 저장소 소스 업데이트 (Git Submodule 활용)
- https://github.com/m-cmp/m-cmp 저장소 Readme 및 사용 방법 업데이트 
- https://github.com/m-cmp/m-cmp 릴리스 관련 문서 업데이트 및 릴리스 생성 (v0.2.0). 끝.

**Comment by seokho-son** [comment]
M-CMP v0.2.0 릴리스 추진 계획)에 따라,

CB-Tumblebug(mc-infra-manager) v0.8.11 프리릴리스 및 API 문서를 공유 드립니다.

- CB-TB v0.8.11
  - 링크: https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.8.11
  - 비고: CB-Tumblebug이 활용하는 CB-Spider의 버전은 v0.8.16이며, https://github.com/cloud-barista/cb-tumblebug/blob/main/scripts/runSpider.sh 를 활용하여 구동하는 것을 가이드 드립니다. (해당 docker 실행 도구에, 연동 가능 버전이 명시되어 있습니다.)
  - 비고: 이번 통합 작업에서는 CB-Spider API는 CB-Tumblebug 이외의 다른 서브시스템이 호출할 필요가 없습니다.
- CB-TB v0.8.11 API 문서 (Swagger API dashboard)
  - 링크: https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/v0.8.11/src/api/rest/docs/swagger.yaml
- 통합 관련 주요 API 활용 가이드: 
  - 링크: https://github.com/cloud-barista/cb-tumblebug/discussions/1570
- CB-TB v0.8.11 서버 구동 및 사용 가이드 
  - 링크: https://github.com/cloud-barista/cb-tumblebug 

해당 CB-TB v0.8.11는 다른 서브시스템과 순차 연동을 위한 (완료) 버전입니다.
- v0.8.11를 활용하여, 연동 작업을 진행하시면 됩니다. (mc-observability, mc-application-manager, mc-workflow-manager, mc-web-console)
  - https://github.com/cloud-barista/cb-tumblebug/discussions/1570 에 주요 API 활용법이 간략하게 포함되어 있습니다.
- main 브랜치는 계속 개선될 예정이라 이를 활용하셔도 됩니다. 그러나, 가급적 API는 변경하지 않을 예정이며, API에 변경이 있는 경우에는 공지하도록 하겠습니다.

**Comment by seokho-son** [comment]
M-CMP 릴리스 및 통합 추진을 위한 회의 주요 사항들을 공유 드립니다.

통합에 다소 시급한 사항들은 (action item)으로 표기하였습니다. 참고하시기 바랍니다.
- (action item) 통합 기능 중심의 API 문서 제공 시급 (시급)
- (action item) 타 서브시스템에서 연동 가능한 버전 릴리스 예상 시점 공유 (시급)

-----

[주요 논의 및 확정 사항]

(전체)
- M-CMP 플랫폼 통합 및 v0.2.0 릴리스 계획 공유됨. 일정 등 확인.
- 기본 시나리오에 이견 없음. 시나리오에 관련된 기본 기능은 자체 추가하면 된다는 것 확인.
- 서브시스템별 API 문서(기능 개발 여부와 별개로) 공유 시급성 공유 완료. (예정된 일정에서 지연된 상태)
- 서브시스템별 1차 연동 완료 일정 수립 필요. (1개월 내에 상호 통합이 추진되어야 하므로, 시급성 인지)
- 서브시스템별 연동 테스트를 위해서는 각 기관에서 자체 구축 후 진행.
- 통합 작업과 별개로 올해 목표를 위한 기능 구현은 병행 추진 필요 당부.
- DockerFile 제공 작업 선행 필요(이후 ETRI에서 CI 워크플로우 제공 예정), 별도의 설명 없이 구동해볼 수 있도록 설치 방법 제공 및 리드미 보완 필요.
- JAVA로 개발하는 기관들의 경우, 상호 리뷰를 통해 저장소 일관성 향상 및 개선 추진 필요.
- CB-Tumblebug 서버 구동 및 API 사용 방법 상세 공유 완료.

(Observability)
- (action item) 통합 기능 중심의 API 문서 제공 시급 (시급)
- (action item) 타 서브시스템에서 연동 가능한 버전 릴리스 예상 시점 공유 (시급)
- 모니터링 에이전트 자동 설치 방안 마련 필요 (v0.2.0에서는 CB-TB의 원격 커맨드 API/또는 직접 SSH를 통해서 에이전트설치 스크립트 실행하는 것이 방안으로 협의됨)
- 에이전트 기반 모니터링 개발 현황 공유 필요 (이노그리드에서 주도하여 추진하는 것으로 기 협의된 사항이며 지연되고 있는 상황)
- 통합 이외의 논의 이슈(Kapaciter, Opensearch, LogStash 활용, 로그 수집 대상 및 범위 등)가 간략히 공유되었으나, 해당 사항들은 이노그리드에서 별도 이슈화 및 논의 필요

(Cost-optimizer)
- v0.2.0 통합에서 제외 협의 완료
- 비용최적화를 위해서, Observability 인프라 리소스 모니터링 활용 예정 (향후, 이노그리드와 상호 협의 진행 예정)
- 올해 성능 목표 (비용최적화 알고리즘 3건) 자체는 조정 불가 (수준은 조율 가능하며, 완벽할 필요 없음)
- 관리 가능한 VM수 등의 성능 목표는 비용최적화에는 해당하지 않으므로 고려 필요 없음 (ETRI 김병섭 책임 확인)

(Application-manager, Workflow-manager)
- 애플리케이션 등록 기능(SW 저장소 및 카탈로그) 등은 이번에 통합 어려움(미리 등록한 애플리케이션 리스트 확인 및 배포는 가능하며 통합 대상임). 합의 완료
- 시나리오 테스트용 애플리케이션은 스트라토가 제시한 웹 및 DB 계열의 일반적인 애플리케이션(3종 이상)으로 진행하는 것으로 합의 완료 (v0.2.0 한정)
- K8s에 애플리케이션 배포를 위해서 CB-TB의 클러스터 생성 기능 테스트 시도 현황 공유, 향후 ETRI에서 정상 동작하는 버전을 구축하여 프리릴리스 버전 공유 예정. (단, v0.2.0 통합 대상은 아님)
- Application, Workflow 두 서브시스템 모두 API와 WebUI 제공하는 것이 v0.3.0 형상 (메가존 웹콘솔에서는 각 WebUI를 연결)
- (action item) 통합 기능 중심의 API 문서 제공 시급 (시급)
- (action item) 타 서브시스템에서 연동 가능한 버전 릴리스 예상 시점 공유 (시급)

(Web-console)
- 통합 일정은 각 서브시스템의 API 문서 공유 이후에 수립 진행 (현재 CB-TB만 API가 공유된 상황이며, 해당 API를 연동하는데는 이슈 없음)
- 메가존의 경우, 연동 대상이 되는 각 서브시스템의 배포 지원 협조 필요 (사유: 모든 서브시스템이 연계되어 있음)
- CLI는 v0.2.0 에서 시급한 기능이 아니므로 통합 대상 제외
- IAM은 CB-TB만 연동 테스트 진행 후 통합 포함 여부 판단. (인증이 타 서브시스템에는 영향이 없는 선에서 추진)
- 연계될 WebUI 간의 일관성 향상을 위해서, 메가존에서 스타일 양식을 공유 예정 (to 스트라토, 옵스나우)
- 애플리케이션 배포, 워크플로우 실행 GUI를 메가존 웹콘솔에 포함할지는 공유될 API 문서 확인 후 판단 예정

(Across-service-manager)
- 개발 기능 및 소스 변경 이슈로 v0.2.0 통합에서는 제외 협의됨

**Comment by kyuengmanKim** [comment]
M-CMP mc-observability v0.2.0 릴리스 계획 공유 드립니다.  

상세 일정은 아래와 같습니다.

---


~ 05/25(토)
- MC-Observability Agent API 명세 공유 (이하 MCMP-Agent)

 

~ 05/31(금)
- MCMP-Agent 사용 가이드 및 시나리오 문서 공유
- MCMP-Agent 수동 설치 가이드 제공
- 사내 테스트 환경 구축 및 접속정보 공유(※일정 변경 가능)
- MCMP-Agent v0.2.0 source code 1차 릴리즈

 

~ 06/07(금)
- CB-TB 이용 MCMP-Agent 설치 가이드 및 API 제공
- MCMP-Agent v0.2.0 source code 2차 릴리즈(버그 수정 및 설치 API 추가)

 

~ 06/17(월)
- MCMP-Agent v0.2.0 source code 최종 릴리즈

**Comment by seokho-son** [comment]
MC workflow manager 일정 공유

06/04(화)
- MC workflow manager 0.2.0 api 명세 공유

06/05(수)
- MC workflow manager 통합기능 위주 시나리오 및 api가이드 공유

06/07(금)
- MC workflow manager 0.2.0 1차 릴리즈(통합기능 위주)
- MC workflow manager 수동설치가이드 및 1차 컨테이너 이미지 공유
- MC workflow manager 중 frontend 일부 기능 소스 및 컨테이너 이미지 공유

06/12(수)
- 테스트환경 접속정보 공유

06/18(화)
- MC workflow manager 0.2.0 2차 릴리즈

**Comment by seokho-son** [comment]
@pbcccbeatboard-strato 안녕하세요! 릴리스 리드 손석호 입니다.
변경된 전체 일정 참고하셔서, workflow-manager 관련 세부 일정 조정이 필요하신 경우, 댓글로 남겨주시면 감사하겠습니다. :)
(cc: @sykim-etri )

**Comment by seokho-son** [comment]
To-do (workflow-manager, application-manager)

![image](https://github.com/m-cmp/m-cmp/assets/5966944/d212182a-e15f-425b-9dc1-a8be8313975d)

**Comment by seokho-son** [comment]
To-do (web-console, iam-manager)

![image](https://github.com/m-cmp/m-cmp/assets/5966944/b18006c2-9c87-4fbe-88e3-3fc900fa0809)

**Comment by seokho-son** [comment]
To-do (observability)

![image](https://github.com/m-cmp/m-cmp/assets/5966944/6b76352b-0ca2-464e-9469-0e1d903f7be6)

**Comment by seokho-son** [comment]
To-do (cost-optimizer)

![image](https://github.com/m-cmp/m-cmp/assets/5966944/2afdc2fa-47a1-4c0d-aa1f-48b9a90d1fd4)

**Comment by powerkimhub** [comment]
- [mc-infra-connector v0.2.0](https://github.com/m-cmp/mc-infra-connector/releases/tag/v0.2.0) 배포 완료

**Comment by seokho-son** [comment]
Completed by https://github.com/m-cmp/m-cmp/pull/8
