### ISSUE TITLE
M-CMP v0.3.0 release

### ISSUE THREAD

**Issue by seokho-son** [m-cmp/m-cmp#9]
# M-CMP v0.3.0 릴리스 추진 계획

## 릴리스 일정 및 대상

- 릴리스 리드 : (주) @seokho-son , (부) 각 저장소 메인테이너
- 최종 릴리스 목표일: **2024. 11. 08(금) 오후 3시**
- 통합 테스트 목표일: **2024. 10. 17(목) 오후 3시**

- 릴리스 대상 저장소 (check: 완료)
  - [x] https://github.com/m-cmp/mc-iam-manager
  - [x] https://github.com/m-cmp/mc-web-console
  - [x] https://github.com/m-cmp/mc-admin-cli
  - [x] https://github.com/m-cmp/mc-workflow-manager
  - [x] https://github.com/m-cmp/mc-application-manager
  - [x] https://github.com/m-cmp/mc-data-manager 
  - [x] https://github.com/m-cmp/mc-observability
  - [x] https://github.com/m-cmp/mc-cost-optimizer
  - [x] https://github.com/m-cmp/mc-infra-manager (submodule: CB-Tumblebug)
  - [x] https://github.com/m-cmp/mc-infra-connector (submodule: CB-Spider)

- API 문서
  - https://github.com/m-cmp/m-cmp/issues/13

## 통합 및 연동 테스트 방법 (담당: 전체)

![image](https://github.com/user-attachments/assets/6233e30c-d979-4042-acb2-644b89652193)

- 통합 및 연동 테스트 목적 (v0.3.0)
  - 서브시스템간 API 및 GUI를 통해 기능을 유기적으로 수행할 수 있는 통합 시스템 기반 확보 
  - M-CMP v0.3.0 포함 기능은 올해 풀 스펙을 목표로 함
  - M-CMP v0.3.0 단일 플랫폼으로 시연 예정 (11월 초)
  - 시스템 주요 성능 목표치
    - 6종 클라우드 연동 및 관리 (리드: mc-infra-connector)
      - (특이사항없음) AWS, GCP, ...
    - 7종 클라우드 자원 및 서비스(리드: mc-infra-connector, mc-infra-manager)
      - (특이사항없음) VPC, VM, K8s, ...
    - 30개 리전 / 500개 VM의 통합 운용 (리드: mc-infra-manager)
      - (미리계획불가) 목표달성에 포커스
    - 2종 외부 이벤트 연계 자동화 지원 (리드: mc-observability)
      - (확정) Slack, Email
    - 3종 서비스 운용 최적화 정책 지원 (리드: mc-cost-optimizer)
      - (확정) 이상비용탐지, 미사용자원탐지, Right sizing
    - 1종 클라우드간 연계 서비스 지원 (리드: mc-data-manager)
      - (확정) Data migration/backup
    - 2종 멀티 클라우드 인사이트 제공 (리드: mc-observability)
      - (확정) Metric 데이터 이상 탐지 기능, Metric 데이터 예측 기능

- 기본 연동 시나리오
  - [운영자] 환경 구성
    - 1) 시스템 구동 및 환경 설정 (플랫폼 접근 계정/접근 제어 처리 등)
    - 2) 애플리케이션 등록

  - [사용자] 서비스 생성 및 활용(워크플로우 미활용)
    - 1) 웹 콘솔 접속
    - 2) 애플리케이션 리스트 조회 및 선택
    - 3) VM/K8s 인프라 생성
    - 4) 애플리케이션 배포
    - 5) 애플리케이션 접속 및 활용
    - 6) 인프라 모니터링/트레이싱/로깅
    - 7) 클라우드 비용(사용량) 확인
    - 8) VM/K8s 인프라 종료 및 삭제

  - [사용자] 서비스 생성 및 활용(워크플로우 활용)
    - 1) 웹 콘솔 접속
    - 2) WF 등록 (인프라 및 애플리케이션 배포 구성)
    - 3) WF 조회/실행 (인프라 및 애플리케이션 통합 배포)
    - 4) 애플리케이션 접속 및 활용 
    - 5) 인프라 모니터링/트레이싱/로깅
    - 6) 클라우드 비용(사용량) 확인
    - 7) VM/K8s 인프라 종료 및 삭제 (또는 삭제 WF 실행)

  - [운영자/사용자] 운용 중 서비스 관리
    - 멀티 클라우드 이벤트/알람 정책 등록 및 동작 확인 (2종 외부 이벤트 연계 자동화 지원)
    - 멀티 클라우드 인사이트 정책 및 동작 확인 (2종 멀티 클라우드 인사이트 제공)
    - 멀티 클라우드 데이터 백업/복구/마이그레이션 (1종 클라우드간 연계 서비스 지원)
    - 멀티 클라우드 서비스 비용 최적화 정책 등록 및 동작 확인 (3종 서비스 운용 최적화 정책 지원)

![image](https://github.com/user-attachments/assets/2945bcb8-d941-4a0a-905d-48687b0d2502)

- 통합 연동 시험 형상
  - VM 인프라: 6종 CSP (AWS, Azure, GCP, NCP, Alibaba, Tencent) 별 VM 1 개 (Ubuntu 22.04 또는 Ubuntu 20.04) 
  - K8s 인프라: 3종 CSP (*Azure, Alibaba, Tencent)
    - 특이사항
      - Azure: Upgrade K8s Version 기능 미제공 (API: /ns/{nsId}/k8scluster/{k8sClusterId}/upgrade)
      - NHN: NHN 콘솔에서 인터넷게이트웨이 생성 및 설정 필요

  - APP 3종 * 2개
    - 카테고리 3종 * 카테고리별 2개의 app (멀티클라우드 활용 효과가 있는 app: application-manager 제안 및 협의) 
    - VM, K8s 인프라 환경 기반 APP

서브시스템간 연동 테스트 시에도, 각 기관에서 6종에 대해 직접 테스트 (계정 자체 처리)

### 통합 세부 일정

| 완료일정           | 작업                                                               | 대상 저장소 | 비고              |
| ---  | ---  | --- | --- |
| **08-14(수)** | 각 서브시스템별 예정 API 문서 공유 |  API 제공하는 통합 대상 저장소 전체     | Swagger API v2.0 문서 제공 (실제 구동 여부 무관), 릴리스 대상 API 리스트 및 활용 순서와 방법 공유 |
| **08-29(목)** | mc-data-manager v0.2.0 릴리스   |  mc-data-manager    | m-cmp v0.2.0 저장소 구성 준수 및 플랫폼 연동 기반 확보 등 |

* API 제공시에는 간단한 기능 활용 방법 제시 필요
* mc-data-manager의 경우, 기본 소스코드가 있는 신규 저장소이며, 1차로 v0.2.0 수준의 저장소 구성 및 시스템 연동을 우선 제공 필요

| 완료일정           | 작업                                                               | 대상 저장소 | 비고              |
| ---  | ---  | --- | --- |
| **09-05(목)** | 각 서브시스템 기능 프리릴리스 완료 (cb-spider, cb-tumblebug)       |  cb-spider, cb-tumblebug     | cb-spider -> cb-tumblebug 연동 테스트 |
| **09-20(금)** | 각 서브시스템 기능 프리릴리스 완료 (mc-observability)       |  mc-observability     | {cb-tumblebug -> VM/K8s} -> mc-observability 연동 테스트 (타 서브시스템에 모니터링 조회 기능 부분에 의존성 있음) |
| **09-30(월)** | 각 서브시스템 기능 프리릴리스 완료 (mc-application-manager, mc-workflow-manager)       |  mc-application-manager, mc-workflow-manager     | cb-tumblebug -> {mc-application-manager, mc-workflow-manager} 연동 테스트 |
| **09-30(월)** | 각 서브시스템 기능 프리릴리스 완료 (mc-cost-optimizer)       |  mc-cost-optimizer     | {{cb-tumblebug -> VM/K8s} -> mc-observability(monitoring)} -> mc-cost-optimizer 연동 테스트 |
| **09-30(월)** | 각 서브시스템 기능 프리릴리스 완료 (mc-data-manager)       |  mc-data-manager     | mc-data-manager 시나리오 연동 테스트 (독자적 GUI로 테스트. GUI 연동 이외에 API 기반 연동은 제외.) |
| **10-14(월)** | 각 서브시스템 기능 프리릴리스 완료 (mc-web-console, mc-admin-cli, mc-iam-manager)       |  mc-web-console, mc-admin-cli, mc-iam-manager     | {전체} -> mc-web-console, mc-admin-cli, mc-iam-manager 연동 테스트 (API 기반, Web 임베이딩 기반) |
| **10-16(수)**   | 통합 시나리오 연동 및 테스트 완료    |    통합 대상 저장소 전체     |  mc-web-console을 통해 시나리오 구동 확인  |

* 일부 기능의 개발이 진행 중이더라도, 일정에 맞춰 우선 프리릴리스 필요 (개별 기능의 완성도 보다 통합의 우선순위가 높음)
* 단, 시스템 또는 전체 기능의 구동이 어려운 경우, 미리 일정 조정 요청 필요
* 저장소 중 일부는 별도의 웹 서버를 제공해야 하며, 이는 mc-web-console 에 임베이딩 되어야 하므로, 세부 기능별 일정은 상기 일정과 차이가 있을 수 있음

| 완료일정           | 작업                                                               | 대상 저장소 | 비고              |
| ---  | ---  | --- | --- |
| **10-17(목)**  | M-CMP 각 서브시스템 v0.2.x 프리릴리스      |    통합 대상 저장소 전체     |   |
| **10-31(목)**     | 각 서브시스템별 최종 확인/보완 및 각 서브시스템 저장소 v0.3.0 릴리스       | 통합 대상 저장소 전체   | 
| **11-07(목)**     | 각 서브시스템 저장소 v0.3.0 릴리스 주요 기능 시연 동영상 제작       | 통합 대상 저장소 전체   | 
| **11-08(금)**    | M-CMP platform v0.3.0 release                | m-cmp/m-cmp 저장소 |   |

* 일정에 이슈가 있는 경우, 미리 이슈화 및 조율 필요 (단, 주요 일정은 조정이 어려움)

## 통합 플랫폼 릴리스

**<ins>담당: ETRI 멤버</ins>**

각 장소의 Pre-release v0.2.x 및 통합 테스트 수행사항을 바탕으로 통합 플랫폼 릴리스를 진행

- https://github.com/m-cmp/m-cmp 저장소 소스 업데이트 (Git Submodule 활용)
- https://github.com/m-cmp/m-cmp 저장소 Readme 및 사용 방법 업데이트 
- https://github.com/m-cmp/m-cmp 릴리스 관련 문서 업데이트 및 릴리스 생성 (v0.3.0). 끝.

**Comment by seokho-son** [comment]
- M-CMP 플랫폼 인증/인가 기능에 대한 내부 서브시스템 통합 적용 여부
  - 이번 릴리스에서는 전체 서브시스템의 API에 적용하지는 않으며, 기 진행된 CB-TB API와 통합 예시로 간소화
- Cloud API 인증/인가 (임시 자격 증명 등) 릴리스 포함 여부
  - 이번 릴리스에서 포함하지 않음

**Comment by MZC-CSC** [comment]
다음 내용 확인했습니다.
. 이번 릴리스에서 mc-iam-middleware 적용은 infra-manager만 대상으로 한다.
. 임시자격증명 릴리스 미포함.


관련 framework에서 해당내용 확인도 부탁드립니다.
1. 1개 CSP에 대하여 multi credential을 가져갈 것인지
    . ex) aws에 동일 account의 full권한 credential A, aws에 read-only 권한 credential B 등
    
2. workspace를 사용하는 fw는 사용 시니라오를 알려주시면
   호출에 필요한 api를 알려드리도록 하겠습니다( from mc-iam-manager)
   
3. iframe을 제공하는 fw에서는 해당 page에서 필요한 data를 알려주시기 바립니다.( to 각 framework )
   요청에 대한 인증부분은 이번릴리즈 대상이 아니므로 page에서 data처리에 필요한 parameter ( ex. nsId, vmId 등)를 알려주시면 좋겠습니다.

**Comment by MZC-CSC** [comment]
추가 요청사항입니다.
MC-ADMIN-CLI 에서 플랫폼 CLI 통합 시험을 위해서는
각 Framework의 swagger 와 더불어 Dockerfile 과 docker를 이용하여 fw를 설정하고 띄우는 방법 가이드가 필요합니다.
현재 repo에 해당 내용이 없는 fw들이 많습니다. 
admin-cli 관점에서 통합에 포함할지 제외할지 여부를 판단할 수 있게 일정이나 포함여부를 알려주시기 바랍니다.

**Comment by MZC-CSC** [comment]
@all
mc-admin-cli에서 사용할 docker-compose.yaml 파일 작성을 위한 각 Framework에서는 [ETRI Docker Hub](https://hub.docker.com/u/cloudbaristaorg)에 각자 자체 제작한 Docker 이미지의 Push(Git Action활용)가 필요하며,  **[ETRI Docker Hub](https://hub.docker.com/u/cloudbaristaorg)에 Push된 Docker 이미지와 함께 Framework 구동을 위해 필요한 연계된 Docker 이미지(예:MySQL) 기반으로 구동하는 방법**에 대한 가이드(README에 서술) 가 필요합니다.   
세부 내용은 아래 Wiki 글을 참고 부탁드립니다.
https://github.com/m-cmp/mc-admin-cli/wiki/Docker%E2%80%90Compose-%EC%9E%91%EC%84%B1-%EA%B4%80%EB%A0%A8

**Comment by hyeon-inno** [comment]
[협의 필요 이슈]
 - 인프라 모니터링
   - 인프라 모니터링의 구동 환경에 대한 제약 사항 규정
   - 여러 사용 시나리오에 대해 구동가능한 환경으로 개발을 고려하다보니 초기에 전체적인 흐름을 파악하는데 이슈가 있음을 확인
   - 따라서 기존에 구성했던 환경은 별첨으로 아카이브 후 기본 구동환경 시나리오에 대한 내용을 정의하려고 합니다.
   - 주요 골자는 각 인프라간 네트워크 통신이 가능함을 기준점으로 삼으려고 하며, 기존 시나리오는 각 인프라간 폐쇄성을 지니는 경우에 적용 가능한 모델로 시나리오를 정의하고자 합니다.
 - 이벤트 알람/트리거
   - 알림 발송 기능 메시징 플랫폼 협의(Slack,Teams 등)
 - 인사이트 2종
   - 'Metric 데이터 이상 탐지 기능'과 'Metric 데이터 예측 기능' 을 제공하려고 고려 중에 있습니다.
   - Metric 데이터 이상 탐지 기능
     - 수집된 Metric 데이터를 분석하여 통계 기반의 이상 탐지
     - 표준 또는 일반적인 분포에서 벗어난 데이터 포인트 식별 기능
   - Metric 데이터 예측 기능
     - 머신 러닝을 사용하여 미래의 메트릭을 예측
     - CPU 환경에서 활용 가능한 범용성 높은 예측 모델 또는 기법 적용

[주요 개발 일정]
~ 08/14 인프라 모니터링/이벤트 알람/트리거 API 초안 공유
~ 08/23 인사이트 제공 모듈 및 기능 설계
~ 08/30 인사이트 API 초안 공유, 인프라 모니터링/이벤트 알람/트리거 활용 가능 초기 버전 업로드
~ 09/20 인사이트 모듈 활용 가능 초기 버전 업로드
~ 10/14 테스트 및 안정화

**Comment by sykim-etri** [comment]
[K8s 인프라 지원 계획 안내]

연동 시험 형상 중 K8s 인프라와 관련한 지원 계획을 안내 드립니다.
cb-tumblebug의 기능 프리릴리스 완료 일정(9/5)을 감안하여 일부 제약사항을 포함하여 진행할 예정입니다.

* 지원 CSP(3종)
  * Azure, Alibaba, NHN
* 제약사항
  * Azure: Upgrade K8s Version 기능 미제공 (API: /ns/{nsId}/k8scluster/{k8sClusterId}/upgrade)
  * NHNCloud: 인터넷게이트웨이의 콘솔 생성 및 설정 필요

**Comment by heedaeshin** [comment]
#### [ Data Manager 지원 계획 안내 ]
##### 1. 지원 대상 CSP Pairs
  - AWS ↔ GCP: 양방향 지원
  - AWS ↔ NCP: 양방향 지원
  - GCP ↔ NCP: 양방향 지원


#####  2. 지원 DB 서비스 종류
- 관계형 데이터베이스 (RDB):
    > 주요 RDBMS (예: MySQL, MariaDB 등 ) 지원
- NoSQL 데이터베이스:
    > 주요 NoSQL DBMS (예: MongoDB 등) 지원


##### 3. 지원 스토리지 종류
  - 오브젝트 스토리지 (Object Storage):
    > 각 CSP의 주요 오브젝트 스토리지 서비스 (예: AWS S3, GCP Cloud Storage, NCP Object Storage 등) 지원


##### 4.  테스트 데이터 사이즈
  - 1GB 내외로 CSP Pairs 체크

**Comment by SungWoongz** [comment]
@sykim-etri 

안녕하세요. azure k8s 인프라 테스트 중 다음과 같은 제약 사항이 있는 것 같습니다.
(API: POST  /ns/{nsId}/k8scluster)

Azure는 cluster upgrade 뿐만 아니라 create에도 제약이 있는 것인지 확인 부탁드립니다.

![image](https://github.com/user-attachments/assets/7e7b310a-dd53-4ea6-a72e-0d244efe2b4a)

**Comment by sykim-etri** [comment]
> @sykim-etri
> 
> 안녕하세요. azure k8s 인프라 테스트 중 다음과 같은 제약 사항이 있는 것 같습니다. (API: POST /ns/{nsId}/k8scluster)
> 
> Azure는 cluster upgrade 뿐만 아니라 create에도 제약이 있는 것인지 확인 부탁드립니다.

@SungWoongz 
벌써 테스트해 주셔서 감사드립니다.^^

conf/cloud_conf.yaml - cloud - azure - k8scluster - enable - "y"로 변경하시면 진행이 가능한데,
최근에 관련 변경 사항을 업데이트(PR)하였기에 최신 버전을 받으시면 해소될 것으로 기대됩니다.

**Comment by pbcccbeatboard-strato** [comment]
안녕하세요 이번 app 배포 테스트 시 진행할 6종 app관련되어 예정으로 진행 중인 것들 공유 드립니다.
혹시 이 외에 추천 하실 만한 것이 있다면 테스트 후 적극 고려하거나, 별도로 추가 하겠습니다.
VM과 k8s에서 모두 설치하려고 하다 보니 생각보다 머릿속에서 선택의 폭이 좁네요

예비 항목으로 작성 해 놓은 것은 테스트 중, 또는 사용 중 이슈가 있을 경우 대체할 예정인 항목이며,
이번 릴리즈에 k8s 또는 VM 둘 중 하나라도 제공하려 하는 항목입니다.

webserver/was category    nginx, tomcat (예비 apache)
rdb/noSql category            mariaDB, redis (예비 mongoDB, postgre)
observability category       prometheus, grafana

**Comment by seokho-son** [comment]
> 안녕하세요 이번 app 배포 테스트 시 진행할 6종 app관련되어 예정으로 진행 중인 것들 공유 드립니다. 혹시 이 외에 추천 하실 만한 것이 있다면 테스트 후 적극 고려하거나, 별도로 추가 하겠습니다. VM과 k8s에서 모두 설치하려고 하다 보니 생각보다 머릿속에서 선택의 폭이 좁네요
> 
> 예비 항목으로 작성 해 놓은 것은 테스트 중, 또는 사용 중 이슈가 있을 경우 대체할 예정인 항목이며, 이번 릴리즈에 k8s 또는 VM 둘 중 하나라도 제공하려 하는 항목입니다.
> 
> webserver/was category nginx, tomcat (예비 apache) rdb/noSql category mariaDB, redis (예비 mongoDB, postgre) observability category prometheus, grafana

@sykim-etri 상기 제안 내용, 컨소시움 내에서 공유 및 협의될 수 있도록 조율 부탁 드립니다.

**Comment by sykim-etri** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-08-13T16:46:05
          
          
            * 메일 제목 : 
Re: [m-cmp/m-cmp] M-CMP v0.3.0 release (Issue #9)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람의 메일함 용량이 가득 찼습니다.
받는 사람에게 메일함 정리를 요청하신 후 다시 발송해 보세요.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by seokho-son** [comment]
CB-Tumblebug(mc-infra-manager) 릴리스 대상 API 공유
- CB-TB 버전: v0.9.5
  - 관련 컴포넌트 버전: https://github.com/cloud-barista/cb-tumblebug/blob/v0.9.5/docker-compose.yaml
- CB-TB API: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/v0.9.5/src/api/rest/docs/swagger.yaml
  - 주의: MCIS 텀은 모두 제거, **MCI** 텀으로 변경 (#1722)
- 사용방법 요약: https://github.com/cloud-barista/cb-tumblebug/discussions/1731

**Comment by kyuengmanKim** [comment]
안녕하세요. 이노그리드 김경만 전임 연구원입니다.  

우선 지난주 M-CMP 컨소시움 온라인 회의에서 논의한 "2종 멀티 클라우드 인사이트 제공" 기능과 관련하여
'단일 VM에 대한 인사이트 기능이 아닌 멀티 클라우드 환경에 대한 인사이트 제공',
'멀티 클라우드 통합', '여러 CSP간 분석 또는 CB-Tumblebug의 MCIS 그룹 단위 분석' 등을 고려하는 것이 필요하다는 의견이 나왔습니다.

이에 대해서 기존 정의한 인사이트 제공 기능  
'1) 모니터링 데이터 예측 기능', '2) 모니터링 데이터 이상탐지 기능'   
위 기능에 ***분석 대상을 단일 VM 또는 그룹 단위로 지정할 수 있는 옵션을 추가***로 제공하고자 합니다.

**_그룹에 대한 개념은 Cloud-Barista의 CB-Tumblebug이 관리하는 Namespace를 활용하고자 합니다._**  
CB-Tumblebug 내용을 살펴본 결과, Namespace > MCIS > SubGroup > VM 순서로 그룹핑하여 관리하는 것으로 보여지므로 우선 가장 큰 범위인 Namespace를 적용하면 좋을 거 같습니다.
분석 대상을 Namespace로 지정하는 경우 해당 ID에 속하는 모든 VM을 평균으로 집계하여 분석하여 정보를 제공합니다.

예시로 'A' Namespace에 대한 CPU 사용률 예측 데이터 요청 시, 'A' ns에 속한 VM List 조회 후 시간, 공간 평균 집계하여 예측을 진행하고 최근(모니터링 데이터) 'A' ns의 평균 CPU 부하률과 이후(예측 데이터)를 함께 제공합니다. 추가로 'A', 'B', 'C' ns 에 대해 개별 요청 시, 각각의 ns 별 CPU 사용률 현황과 이후 추세를 비교할 수 있습니다.
이에 대한 의견 공유해주시면 감사하겠습니다.  
인사이트 제공 2종에 대한 정의가 완료되는 대로 기능 설계 및 API 도출을 진행할 계획입니다.  

상세 기능에 대한 정의는 아래와 같습니다.  

## 모니터링 데이터 예측 기능

### 기능 정의
- **단일 VM 또는 Namespace 그룹 단위 분석 제공**
- 머신 러닝을 사용하여 미래의 메트릭을 예측
- CPU 환경에서 활용 가능한 범용성 높은 예측 모델 또는 기법 적용

### 주요 지원 기능
- 모니터링 데이터 예측 기능
  - 예측 요청 API
- 예측 데이터 관리 기능
  - 예측 데이터 저장
  - 이전 예측 데이터 조회 API

### 지원 범위
- 실수 타입의 모니터링 모니터링 데이터 - CPU, MEM, Disk, Network Recv/Sent 등
- agent 설치 및 위 모니터링 항목에 대한 모니터링을 진행 중인 VM 또는 Namespace에 속한 VM 그룹 대상
- prediction data interval: 1 hour
- prediction data range: 과도한 리소스 사용을 방지하는 선에서 제한

### 활용 방안
- 멀티 클라우드 활용 계획 수립, 인프라 설계 및 운용 최적화를 위한 예측 데이터 제공
- 인프라 자원 부족에 대한 사전 대비
- VM 리사이징, 비용 최적화 등 관련 참고 지표로 활용

## 모니터링 데이터 이상 탐지 기능

### 기능 정의
- **단일 VM 또는 Namespace 그룹 단위 분석 제공**
- 수집된 모니터링 데이터를 분석하여 통계 기반의 이상 탐지
- 표준 또는 일반적인 분포에서 벗어난 데이터 포인트 식별 기능
- 실시간으로 수집되는 시계열 모니터링 데이터 특성에 적합하고 연산이 빠른 모델 사용
- 사용 모델은 RRCF로 데이터 분포를 효율적으로 모델링하는 트리 기반의 비정상 탐지 모델

### 주요 지원 기능
- 이상 탐지 대상 등록 및 관리 기능
  - 대상 관리 CRUD API
  - Namespace 등록 시 해당 그룹에 속한 VM ID list 조회
- 이상 탐지 결과 데이터 조회 기능
  - 데이터 조회 API
- 지속적인 실시간 이상 탐지를 위한 스케줄링 기능
  - 사용자 등록 대상에 따른 이상탐지 반복 실행 스케줄러

### 지원 범위
- CPU_usage_idle, MEM_used_percent 사용률(%) 모니터링 모니터링 데이터 2종
- agent 설치 및 위 모니터링 항목에 대한 모니터링을 진행 중인 VM 또는 Namespace에 속한 VM 그룹 대상
- 최근 12시간 데이터 분석

### 활용 방안
- 과거 데이터를 분석하여 실시간으로 비정상적인 현상에 대한 판별 기능
- 단순 임계치 기반 장애 알람이 감지할 수 없는 비정상 현상 식별
- 추가적인 장애 관련 인사이트 프로세스의 시작점으로 활용

**Comment by MZC-CSC** [comment]
@seokho-son 
'''
[운영자/사용자] 운용 중 서비스 관리

1. 멀티 클라우드 이벤트/알람 정책 등록 및 동작 확인 (2종 외부 이벤트 연계 자동화 지원)
2. 멀티 클라우드 인사이트 정책 및 동작 확인 (2종 멀티 클라우드 인사이트 제공)
3. 멀티 클라우드 데이터 백업/복구/마이그레이션 (1종 클라우드간 연계 서비스 지원)
4. 멀티 클라우드 서비스 비용 최적화 정책 등록 및 동작 확인 (3종 서비스 운용 최적화 정책 지원)
'''
위 사항에서
1. o11y 
2. o11y 
3. data-manaager 
4. cost-optimizer 에서 
어떤 식으로 수행하는지 예상 시나리오 부탁드립니다.

**Comment by seokho-son** [comment]
> @seokho-son ''' [운영자/사용자] 운용 중 서비스 관리
> 
> 1. 멀티 클라우드 이벤트/알람 정책 등록 및 동작 확인 (2종 외부 이벤트 연계 자동화 지원)
> 2. 멀티 클라우드 인사이트 정책 및 동작 확인 (2종 멀티 클라우드 인사이트 제공)
> 3. 멀티 클라우드 데이터 백업/복구/마이그레이션 (1종 클라우드간 연계 서비스 지원)
> 4. 멀티 클라우드 서비스 비용 최적화 정책 등록 및 동작 확인 (3종 서비스 운용 최적화 정책 지원)
>    '''
>    위 사항에서
> 5. o11y
> 6. o11y
> 7. data-manaager
> 8. cost-optimizer 에서
>    어떤 식으로 수행하는지 예상 시나리오 부탁드립니다.

차기 통합/릴리스 온라인 회의에서, 각 서브프로젝트별로 공유될 예정입니다. 참고하시기 바랍니다.

**Comment by seokho-son** [comment]
Complete !

https://github.com/m-cmp/m-cmp/releases/tag/v0.3.0

But, Additional fixs are required.
